FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma

RUN npx prisma generate

# Copy source files
COPY tsconfig.json nest-cli.json ./
COPY src ./src

# Create dist directory to avoid EBUSY errors
RUN mkdir -p dist

EXPOSE 3000

CMD ["npm", "run", "start:dev"]

